# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  install:
    desc: "Install dependencies"
    cmds:
      - uv sync

  start:
    desc: "Start the application"
    cmd: python main.py
  
  ollama:
    desc: "Start the ollama server"
    cmd: ollama serve

  #task git m="your commit message"
  git: 
    desc: "Git commit"
    cmds:
      - git add .
      - git commit -m "{{.m}}"
    requires:
      vars: [m]

  #task git-push m="your commit message"
  git-push:
    desc: "Git commit and push"
    cmds:
      - git add .
      - git commit -m "{{.m}}"
      - git push
    requires:
      vars: [m]
